final assessment
learn-academy-2022-alpha/week-6-assessment-mrcallenmatias pull request #1
Opened 2022-04-04 05:17 UTC by mrcallenmatias

2022-04-07 05:37 UTC, SunkissedQueen requested changes
Marc, the last assessment! Thank you for always being  on time and giving full effort to your assessments. Please review my notes.

2022-04-07 05:37 UTC, SunkissedQueen commented on code-challenges.test.js
> +
Please include your test suite results

2022-04-07 05:37 UTC, SunkissedQueen commented on interview-questions.md
> +Your answer: I would first need to create a migration folder and would name it related to the foreign key name. In the terminal, I would type rails generate migration (folder name). That would create
Please check out this section of the syllabus. 
https://github.com/learn-academy-2022-alpha/Syllabus/blob/main/rails/associations.md

2022-04-07 05:37 UTC, SunkissedQueen commented on interview-questions.md
> +Researched answer: Show, edit, update and destroy are the only restful routes that always passed params, like their ID as they need to have parameter to pull from for their function to work.
good research

2022-04-07 05:37 UTC, SunkissedQueen commented on interview-questions.md
> +This will call on the NEW method and will show a form use to create a new data for the table student.
glad you remember the form

2022-04-07 05:37 UTC, SunkissedQueen commented on interview-questions.md
> +
User stories can be tricky, especially for developers because our thoughts are on creating the code that will accomplish the task. User stories are more about the user experience with the DOM. What the user can see, click, type...how they get to interact with the web page. So think more of what the user will see on the webpage

2022-04-07 05:37 UTC, SunkissedQueen commented on p.js
> +// Create a function that takes in an array of numbers and returns the sum of all the numbers cubed.
Looks like an extra file got saved.

2022-04-07 05:37 UTC, SunkissedQueen commented on rails-commenting.rb
> +# ---1) This class holds restfull routes that can create, read, update and destroy a database. It is created by typhing rails g controller inside the terminal
What is this relationship showing on Line 10

2022-04-08 19:15 UTC, mrcallenmatias commented on code-challenges.test.js
> +
Hi Charlene. What do you mean by test suites result?

2022-04-09 03:15 UTC, SunkissedQueen commented on code-challenges.test.js
> +
When you run `yarn jest` after creating the test, you receive red FAIL then after creating the function green PASS.  I need you to place those results on here.

2022-04-09 05:01 UTC, SunkissedQueen approved these changes
Thanks for the corrections.

2022-04-11 16:12 UTC, merged